name: abl_app
description: "Aplikasi Manajemen Gudang & Distribusi PT. Abadi Berkat Lestarindo"
publish_to: 'none'

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icon bawaan iOS style
  cupertino_icons: ^1.0.8
  
  # Database
  supabase_flutter: ^2.10.3
  
  # Format Tanggal & Uang
  intl: ^0.20.2
  
  # Font Keren (Poppins, OpenSans)
  google_fonts: ^6.3.2
  
  # Cetak Struk / Invoice
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter agar kodingan rapi
  flutter_lints: ^3.0.0
  
  # Alat pembuat Icon Aplikasi (.exe)
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Mendaftarkan folder gambar agar bisa dibaca aplikasi
  assets:
    - lib/assets/

# --- KONFIGURASI ICON APLIKASI ---
# Pastikan nama file gambar di bawah ini SESUAI dengan file yang ada di folder lib/assets/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/warehouse-logo-1024.png" 
  windows:
    generate: true
    icon_size: 256
    icon_background_color: "#FFFFFF" # Opsional: Background putih jika icon transparan